# Generated by Django 3.0.5 on 2020-04-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('cases_total', models.IntegerField()),
                ('cases_new', models.IntegerField()),
                ('deaths_total', models.IntegerField()),
                ('deaths_new', models.IntegerField()),
                ('transmission_type', models.CharField(max_length=50)),
                ('days_last_case', models.IntegerField()),
            ],
        ),
    ]
